theme = "onedark_perlinm"

[editor]
line-number = "absolute"
gutters = ["diagnostics", "line-numbers", "diff"]
bufferline = "multiple"
color-modes = true
mouse = false
middle-click-paste = false
completion-trigger-len = 1
idle-timeout = 0
auto-pairs = false
auto-format = false

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
auto-signature-help = false

[editor.soft-wrap]
enable = true
max-indent-retain = 100
wrap-indicator = ""

[editor.file-picker]
hidden = false

[keys.normal]
### unbind old keys
# q = "no_op"  # keep default
# g = "no_op"  # keep default
# m = "no_op"  # keep default
j = "no_op"
a = "no_op"
A-c = "no_op"
### cursor navigation
k = "align_view_center"
n = "move_char_left"
i = "move_char_right"
u = "move_visual_line_up"
e = "move_visual_line_down"
l = "goto_first_nonwhitespace"
y = "goto_line_end"
A-n = "move_prev_word_start"
A-N = "move_prev_long_word_start"
A-i = "move_next_word_end"
A-I = "move_next_long_word_end"
A-u = "goto_prev_paragraph"
A-e = "goto_next_paragraph"
A-l = "goto_line_start"
A-y = "goto_line_end_newline"
";" = "half_page_up"
o = "half_page_down"
A-j = "copy_selection_on_prev_line"
A-h = "copy_selection_on_next_line"
"A-;" = "flip_selections"
"A-," = "remove_primary_selection"
### buffer and search
F = ":format"
A-s = ":write"
A-f = ":reload"
"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"
A-w = ":buffer-close"
L = "jump_backward"
Y = "jump_forward"
w = "search_prev"
f = "search_next"
A-r = "search_selection"
### text manipulation
z = "undo"
Z = "redo"
A-z = "undo"
A-Z = "redo"
r = "redo"
"A-/" = "toggle_comments"
p = "open_above"
P = "open_below"
b = "expand_selection"
B = "shrink_selection"
c = "yank"
x = "delete_selection"
v = "paste_before"
V = "paste_after"
C-c = "yank_main_selection_to_clipboard"
C-x = ["yank_main_selection_to_clipboard", "delete_selection_noyank"]
C-v = "paste_clipboard_before"
C-V = "paste_clipboard_after"
A-a = "goto_line_start"
A-k = "kill_to_line_end"
"backspace" = "delete_selection_noyank"
"del" = "delete_selection_noyank"
"`" = "switch_to_lowercase"
"A-`" = "switch_to_uppercase"
### mode control
A-q = ["collapse_selection", "keep_primary_selection"]
"ret" = "insert_mode"
"A-ret" = "append_mode"
t = "insert_mode"
T = "append_mode"
s = "select_mode"
S = "select_regex"
h = "hover"
d = "extend_line_below"
D = "extend_line_above"

[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"
c = "file_picker_in_current_buffer_directory"

[keys.select]
### unbind old keys
# q = "no_op"  # keep default
# g = "no_op"  # keep default
# m = "no_op"  # keep default
j = "no_op"
a = "no_op"
A-c = "no_op"
### cursor navigation
k = "align_view_center"
n = "extend_char_left"
i = "extend_char_right"
u = "extend_visual_line_up"
e = "extend_visual_line_down"
l = "goto_first_nonwhitespace"
y = "goto_line_end"
A-n = "extend_prev_word_start"
A-N = "extend_prev_long_word_start"
A-i = "extend_next_word_end"
A-I = "extend_next_long_word_end"
A-u = "goto_prev_paragraph"
A-e = "goto_next_paragraph"
A-l = "goto_line_start"
A-y = "goto_line_end_newline"
";" = "half_page_up"
o = "half_page_down"
A-j = "copy_selection_on_prev_line"
A-h = "copy_selection_on_next_line"
"A-;" = "flip_selections"
"A-," = "remove_primary_selection"
### buffer and search
F = ":format"
A-s = ":write"
A-f = ":reload"
"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"
A-w = ":buffer-close"
L = "jump_backward"
Y = "jump_forward"
w = "search_prev"
f = "search_next"
A-r = "search_selection"
### text manipulation
z = "undo"
Z = "redo"
A-z = "undo"
A-Z = "redo"
r = "redo"
"A-/" = "toggle_comments"
p = "open_above"
P = "open_below"
b = "expand_selection"
B = "shrink_selection"
c = "yank"
x = "delete_selection"
v = "paste_before"
V = "paste_after"
C-c = "yank_main_selection_to_clipboard"
C-x = ["yank_main_selection_to_clipboard", "delete_selection_noyank"]
C-v = "paste_clipboard_before"
C-V = "paste_clipboard_after"
A-a = "goto_line_start"
A-k = "kill_to_line_end"
"backspace" = "delete_selection_noyank"
"del" = "delete_selection_noyank"
"`" = "switch_to_lowercase"
"A-`" = "switch_to_uppercase"
### mode control
A-q = "normal_mode"
"ret" = "insert_mode"
"A-ret" = "append_mode"
t = "insert_mode"
T = "append_mode"
s = "collapse_selection"
S = "select_regex"
h = "hover"
d = "extend_line_below"
D = "extend_line_above"

[keys.insert]
### cursor navigation
A-n = "move_char_left"
A-i = "move_char_right"
A-u = "move_visual_line_up"
A-e = "move_visual_line_down"
A-l = "goto_first_nonwhitespace"
A-y = "goto_line_end_newline"
### buffer and search
A-s = ":write"
### text manipulation
A-z = ["undo", "normal_mode"]
A-Z = ["redo", "normal_mode"]
C-c = "yank_main_selection_to_clipboard"
C-x = ["yank_main_selection_to_clipboard", "delete_selection_noyank"]
C-v = "paste_clipboard_before"
C-V = "paste_clipboard_after"
A-a = "goto_line_start"
A-k = "kill_to_line_end"
### mode control
A-q = "normal_mode"
